export { default as MainPage } from './MainPage'
export { default as AuthPage } from './AuthPage'
export { default as ArtistPage } from './ArtistPage'
export { default as ArtistsPage } from './ArtistsPage'
export { default as AlbumPage } from './AlbumPage'
export { default as AlbumsPage } from './AlbumsPage'

export { default as ProfilePage } from './ProfilePage'
export { default as CollectionPage } from './CollectionPage'
export { default as BlogPage } from './BlogPage'
