export { default as MainPage } from './MainPage'
export { default as AuthPage } from './AuthPage'
export { default as ArtistPage } from './ArtistPage'
export { default as ArtistsPage } from './ArtistsPage'
export { default as AlbumPage } from './AlbumPage'
export { default as AlbumsPage } from './AlbumsPage'
